.github/workflows/gh-metadata.yml
.github/workflows/python-lib.yml
gh-metadata/README.md
gh-metadata/action.yml
python-lib/README.md
python-lib/action.yml
python-lib/check-version/action.yml
python-lib/publish/action.yml
python-lib/test/action.yml

Inport from internal actions and add support for pypi

Import internal actions

---

python-app/README.md
python-app/action.yml
python-app/docker/action.yml
python-app/goss/action.yml
python-app/lint/action.yml
python-app/test/action.yml

it does lint, unittest, goss and docker image
usage: https://github.com/LedgerHQ/vault-device-api/pull/60

add generic action for python-app

---

python-lib/check-version/action.yml

Bumped checkout version from v2 to v3, and added recursive mode to check out submodules correctly

Updated checkout action and added recursive mode for submodules in check version action

---

python-lib/check-version/action.yml

used wrong access to token variable

Fixed usage of TOKEN from secrets to env in check version action

---

python-app/README.md

just noticed this by using the README
got triggered

[python-app] Fix README by cleaning un-wanted tabs

---

.github/workflows/gh-context.yml
gh-context/README.md
gh-context/action.yml

See https://github.com/LedgerHQ/ledger-vault-api/actions/runs/2804306443/attempts/1#summary-7693437036 for test

Add new action gh-context

---

python-app/docker/action.yml

Updating build and push action according to docker doc to cross build with dockerx: 
https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md

Adding cross-build for ARM arch 

---

python-app/docker/action.yml

This reverts commit 1e0bc44838a5917d29da14f7f1a2c49b41a476d3.
This breaks CI on docker image building.

Revert "Adding cross-build for M1 Mac (#41)"

---

python-app/action.yml
python-app/doc/action.yml
python-app/init/action.yml
python-app/lint/action.yml
python-app/test/action.yml

This reverts commit 4e2df6c46e63c10db2a4a77dc7a4f911d94dfe2b, reversing changes made to d1668266a80050072c1b4675824c4ad90eff4b2c.

Revert "Merge pull request #46 from LedgerHQ/update/python-app-3-10"

---

python-lib/README.md

Python version should be string

Updating the readme

---

documentation/README.md
documentation/c4/action.yml

Add a C4 documentation action

---

.github/workflows/start-linux-runner.yml
gemfury/latest-version/action.yml
gh-metadata/action.yml
python-app/doc/action.yml
python-app/docker/action.yml
python-app/goss/action.yml
python-app/init/action.yml
slack-notification/action.yml

* Removes a lot of deprecation warnings.
* See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

feat: Move to new syntax for set-output

---

python-app/doc/action.yml
redocly/publish/action.yml

Reuse the `redocly/publish` action in `python-app/doc` action to benefit from action error handling

refactor(python-app): reuse the `redocly/publish` action

---

python-app/action.yml
python-app/docker/action.yml
python-app/goss/action.yml

Allow to pass PYPI_DEPLOY_TOKEN via secret

---

cascade-merge/action.yml

[documentation](https://ledgerhq.atlassian.net/wiki/spaces/VAUL/pages/4217405671/Auto+Cascade+Merge) 
experimenting on [this repo](https://github.com/LedgerHQ/cascade-merge-experiment)

VG-14096 add action to auto cascade merge

---

cascade-merge/action.yml

remove check of conflicts as it's already done in previous step

minor refactoring cascade merge

---

cascade-merge/action.yml

- allow a dedicated branch for PR creation
- handle no commits between source and the target branch
- install gh CLI, required for internal CI runners (already installed for github runners)

updates and fixes to CascadeMerge action

---

cascade-merge/action.yml

only use slack if they the creds are provided

for CascadeMerge, Integrate slack on conflicts

---

.github/workflows/vault_helm_lint_publish.yml
helm/README.md
helm/conform/action.yml
helm/lint/action.yml

fix missing inputs 
change helm lint ct config parameters

Fix helm action 

---

redocly/publish/action.yml

https://github.com/LedgerHQ/vault-platform-manager/actions/runs/7411624225/job/20166606618#step:3:40

fix(redocly): publish deprecated command

---

.github/workflows/vault_helm_lint_publish.yml

@noirbizarre ping 
this will be need to reflect recent change

Update how CHARTMUSEUM secret are used

---

helm/README.md
helm/argocd-test/action.yml

Not only running helm template but also kubeconfom

Add kubeconform in argocd helm action

---

pdm/release/action.yml

fix(pdm): add the missing `$INPUT_INCREMENT` environment variable in release (fix #130)

---

pdm/init/action.yml

Ensure `pdm/init` always install all project extras

fix(pdm): ensure init install all extras

---

pdm/release/README.md
pdm/release/action.yml

Adds support for public libraries (published on `PyPI` instead of the internal `Nexus`/`GemFury`).

feat(pdm): support public libraries publication on PyPI

---

pdm/init/README.md
pdm/init/action.yml
pdm/test/action.yml

This PR exports pdm test results to Allure server if some allure results are presents in `reports/allure`.
Link to the report is added to the job summary.
If the job run for a pull request, the report link is also added as a comment to the pull request.

feat(pdm): export test result to Allure server if supported

---

pdm/test/README.md
pdm/test/action.yml

Fix `pdm/test` action which can't access `vars` and `secrets`.
Added `allure-username` and `allure-password` optional inputs.
Accept `BACKSTAGE_URL` as optional environment variable.

fix(pdm): `pdm/test` action can't access `vars` and `secrets`

---

pdm/doc/build/action.yml

Base specification were not renamed properly and diff was failing

fix(pdm): fix openapi specifications filenames for diff

---

pdm/doc/build/action.yml

fix(pdm) fix typo on condition (`steps`)

---

pdm/release/action.yml
pdm/test/action.yml

Workaround Github Actions DSL dumbness (does not support booleans, duh)

fix(pdm): ensure bools are all tested as strings because GitHub Actions DSL does not supports bools

---

.editorconfig
pdm/release/action.yml
python-app/test/action.yml
slack-notification/action.yml

Fix a typo in editorconfig settings.
Fix lints in files not linted due to this typo (bad indentation)

Fix typo in `.editorconfig` and adjust bad indentation in file accordingly

---

pdm/release/action.yml

Fix(pdm): fix typo on release action

---

pdm/release/action.yml

Just make JFrog Artifactory failsafe until it's mandatory

fix(pdm/release): make the Artifactory release failsafe until mandatory

---

pdm/README.md
pdm/doc/build/README.md
pdm/doc/publish/README.md
pdm/docker/README.md
pdm/init/README.md
pdm/release/README.md
pdm/test/README.md

Add some documentation on JFrog Artifactory OIDC and attestations permissions side effects.

doc(pdm): document side-effects of JFrog OIDC auth and permissions

---

pdm/release/action.yml

Allows libraries to also publish docker images if a `Dockerfile` is found

feat(pdm): allows libraries to also publish docker images

---

pdm/release/README.md
pdm/release/action.yml
slack/release/README.md
slack/release/action.yml

Fix release output fields (wrong name and missing extra)

fix(pdm): add missing outputs and notifications

---

pdm/test/README.md
pdm/test/action.yml

Allow to start docker compose during testing

feat(pdm): allows to start Docker Compose during the tests

---

pdm/test/action.yml

I manage to make 2 errors on a single line change: I think I need a coffee ☕ 😅

fix(pdm): fix another typo

---

openapi/diff/action.yml

switch to thollander/actions-comment-pull-request@v3 introduce some breaking changes

fix regression openapi diff

---

pdm/doc/build/action.yml

Fix wrong context used in condition

fix(pdm) fix wrong context in condition

---

pdm/doc/build/README.md
pdm/doc/build/action.yml
pdm/openapi/README.md
pdm/openapi/action.yml

Separate the generation of OpenAPI spec from build/doc action.

feat(pdm): action to generate, lint and upload openapi spec
