- python-app/docker/action.yml
The secrets are not passed through the actions, so we need to directly
use the context, which is available.
> [BUGFIX] Fix GITHUB_TOKEN not available.

- gemfury/latest-version/action.yml
- gemfury/publish/action.yml
- python-lib/README.md
- python-lib/action.yml
- python-lib/publish/action.yml
- python-lib/test/action.yml
As described in https://ledgerhq.atlassian.net/wiki/spaces/VAUL/pages/3639115871/2022-04-12+-+Publish+dev+version+of+python+package we want our python packages to be published as RCs when we push to a feature branch.
The versioning model for these publishes is `<major>.<minor>.<patch>rc<number>+<name.of.the.feature>`.
In this proposal, the publishing is automatic for any `feature/X` branch. The rc number is automatically computed by fetching the last rc and incrementing it. The dev does not have to do any version change manually.
This has required:
- the usage of a new PYPI token, `PYPI_FULL_ACCESS_TOKEN` which allows listing package versions
- forcing a standardised definition of the version in `setup.py` to be able to script its temporary update.
Note that we could alternatively have …
> Auto publish python libs feature branches

- gemfury/latest-version/action.yml
when checking for existing package on gemfury the package name still had uppercase letters when we seem to push the package with only lowercase letters
so the filter is now updated to lowecarse the package name
source:
Package name generated by the CI and used for searching existing version
name of the package on gemfury
> Lowercasing the filter for existing package name

- python-app/action.yml
- python-app/test/action.yml
The `test` action is checking if `mypy` lib is installed on the repo and assume that we want to run Mypy on the codebase then. But that's wrong, in some cases Mypy is just installed because dependency shit hell, and is not properly configured on the project, which makes the mypy fails.
This PR adds a new input flag to allow forcing bypassing the mypy step.
> VG-3365 Option to force ignore Mypy

- python-lib/test/action.yml
Blocking some pipelines as CODECOV_TOKEN is not passed to the action and official codecov action is not used
https://github.com/LedgerHQ/python-smart-contract/actions/runs/4057321835/jobs/6999723239#step:2:886
Related issue on codecov tracker: https://github.com/codecov/codecov-action/issues/557
> feature: decomission codecov

- python-app/doc/action.yml
This PR fixes the `python-app/doc` action: adds the missing but required `shell` property, even if the doc says it is optional
> fix(python-app/doc): add the missing but required `shell` property

- redocly/publish/action.yml
Just a fixed some typos in redocly publish workflow:
- a missing dollar sign (var is currently not extrapolated)
> fix(redocly): fix some redocly typos

- python-app/doc/action.yml
* Should match this parameter name : https://github.com/LedgerHQ/actions/blob/main/redocly/publish/action.yml#L5
> fix(python-app): name compatibility with redocly action

- python-app/action.yml
- python-app/docker/action.yml
- python-app/init/action.yml
with base image on ghcr we need to be login for Goss and docker build. It easier to have it at "init" phase
> login early to ghcr

- .github/workflows/allure.yml
- allure/publish/README.md
- allure/publish/action.yml
Adding a new action to compile and push allure test results to our allure server.
Based off https://github.com/LedgerHQ/vault-e2e-tests/blob/main/.github/workflows/reusable.yml#L281
> feat: add new action to publish test results to allure

- cascade-merge/action.yml
fix targeting the next release branch, when there are +2 next release branches.
> fix in cascade merge

- cascade-merge/action.yml
fix targeting next release branch when there are +2 next-release branches
tested manually
https://github.com/LedgerHQ/cascade-merge-experiment/pulls?q=is%3Apr+is%3Aclosed
> cascade merge fix

- python-app/openapi-diff/action.yaml
Example usage:
```yaml
name: Generate OpenApi Diff
on:
pull_request:
workflow_dispatch:
inputs:
base_ref:
description: "Base branch for the diff"
required: true
default: "main"
head_ref:
description: "Head branch for the diff"
required: false
jobs:
generate-diff:
name: Generate OpenAPI diff
runs-on: ubuntu-latest
steps:
- uses: LedgerHQ/actions/python-app/openapi-diff@main
with:
base_ref: ${{github.event.inputs.base_ref || github.base_ref}}
head_ref: ${{github.event.inputs.head_ref || github.head_ref}}
doc_output: doc/api-spec.yaml
env:
PYPI_DEPLOY_TOKEN: "${{ secrets.PYPI_DEPLOY_TOKEN }}"
> Add OpenAPI diff action

- pdm/README.md
- pdm/doc/README.md
- pdm/doc/action.yml
- pdm/doc/build/README.md
- pdm/doc/build/action.yml
- pdm/doc/publish/README.md
- pdm/doc/publish/action.yml
- pdm/docker/README.md
- pdm/docker/action.yml
- pdm/init/README.md
- pdm/init/action.yml
- pdm/lint/README.md
- pdm/lint/action.yml
- pdm/meta/README.md
- pdm/meta/action.yml
- pdm/release/README.md
- pdm/release/action.yml
- pdm/test/README.md
- pdm/test/action.yml
- slack/README.md
- slack/release/README.md
- slack/release/action.yml
Provides `pdm` actions for the entire lifecycle of a `pdm`-based project, lib or service.
- CI for lib: https://github.com/LedgerHQ/les-copier-demo/actions/runs/7818583568
- CI for service: https://github.com/LedgerHQ/les-copier-demo/actions/runs/7816532564
- CI for service without `goss`: https://github.com/LedgerHQ/les-copier-demo/actions/runs/7802772748
- Release for lib: https://github.com/LedgerHQ/les-copier-demo/actions/runs/7818647647
- Generated GitHub release: https://github.com/LedgerHQ/les-copier-demo/releases/tag/0.3.0
- Generated doc: https://ledgerhq.github.io/les-copier-demo/0.2.0
- Release for service: https://github.com/LedgerHQ/les-copier-demo/actions/runs/7817736451
- Generated GitHub release: https://github.com/LedgerHQ/les-copier-demo/releases/tag/0.2.0
- Generated …
> feat(pdm): add `pdm` actions (VG-14148)

- pdm/release/README.md
Using `|` in the description of `increment` adds columns to the table, in an unexpected way.
Escape `|` to fix the format of the Markdown table.
> fix(pdm/release): fix Markdown table format in README

- pdm/lint/action.yml
- python-app/lint/action.yml
- python-lib/test/action.yml
GitHub Actions workflows are complaning:
> Node.js 16 actions are deprecated. Please update the following actions
> to use Node.js 20: actions/cache@v3. For more information see:
> https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
This was fixed in https://github.com/pre-commit/action/releases/tag/v3.0.1
> fix(deps): bump pre-commit/action from 3.0.0 to 3.0.1

- slack/release/action.yml
This PR ensure the the multiline JSON payload is properly stored as step outputs using GHA dedicated syntax for multiline outputs (cf. https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings)
Fixes #131
> fix(slack/release): use Github Actions heredoc syntax for multiline output (fix #131)

- pdm/release/action.yml
`pdm/release` action was having git messages mixed with the changelog output.
This PR just ensure it's not the case anymore, as git messages are now redirected to stderr.
> fix(pdm): git messages where mixed with the changelog output

- pdm/test/README.md
- pdm/test/action.yml
Allows to specify extra `parameters` to the `pdm cover` in the `pdm/test` action.
> feat(pdm): support some extra parameters to the `pdm cover` command

- pdm/doc/build/README.md
- pdm/doc/build/action.yml
- pdm/doc/publish/README.md
- pdm/doc/publish/action.yml
- pdm/docker/README.md
- pdm/init/README.md
- pdm/init/action.yml
- pdm/release/README.md
- pdm/release/action.yml
- pdm/test/README.md
- pdm/test/action.yml
This PR:
- allows specifying some group exclusions on the `pdm/init` action
- allows customizing the group installed for each action
- ensure that specified groups are given to nested actions
This is especially useful for projects having some heavy optional (not dev) dependencies we don't want to install for each job.
It relies on PDM 2.13 `--without` parameter (https://github.com/pdm-project/pdm/issues/2258) which is automatically installed by those actions
> feat(pdm): allows group exclusion on init/install

- slack/release/action.yml
Typo fix on `slack/release` action
Fix #139
> fix(slack): fix typo preventing payload retrieval (fix #139)

- pdm/init/README.md
- pdm/init/action.yml
- pdm/meta/README.md
- pdm/meta/action.yml
- pdm/release/action.yml
This PR merges `pdm/meta` into `pdm/init` and deprecate `pdm/meta` (but fix it until everybody use `pdm/init` outputs). It should fix #144 
Remarks (that might need to be fixed before merging this PR):
- only `has_*` predicate have been integrated into `pdm/init` because:
- not sure the `sha` is still required (already provided by `github.sha` and no computation on it)
- `target` and `branches` were initially made for the Gate CI which was using `pull_request_target` but this is not the case anymore (tldr. I think we ~can~ should remove this)
- `version` seems to be computed twice (cf. https://github.com/LedgerHQ/actions/blob/main/pdm/docker/action.yml#L51-L60) with different algo
- `pdm/meta` is kept but deprecated to avoid breaking existing workflows using it. Will be removed as soon as …
> refactor(pdm): merge `pdm/meta` into `pdm/init` and fixes outputs (fix #144)

- pdm/init/README.md
- pdm/init/action.yml
- pdm/test/action.yml
This PR:
- fixes the coverage comments on PRs having broken links with `src`-based layouts
- expose a `has_src` helper in `pdm/init` outputs
Fixes #137
> fix(pdm): ensure coverage comment handles `src`-layout and expose a `has_src` metadata (fix #137)

- pdm/release/README.md
- pdm/release/action.yml
This PR make the `pdm/release` action more secure and avoid ending in an unstable state:
- not pushing the tag is considered a failure
- steps relying on CI-only credentials are considered critical (`gemfury`, `nexus`, `docker`):
- can only be executed from CI
- a release is considered failed as soon as one of them fail
- they must be cleaned in the workflow (because they require credentials)
- documentation failure does not stop the release, as it can be published later from anybody with repository permissions
- GitHub release publication failure does not stop the process as it can be manually crafted after
- summary steps are should never make the workflow fail
On failure:
- docker image is deleted if any
- GemFury package is deleted if any
- Nexus package is deleted if any
- Tag …
> feat(pdm): failsafe PDM release (failsafe steps and cleanup on failure)

- pdm/release/action.yml
Add the missing `shell` properties.
Note: we should have a pre-commit and a CI linting actions and validating them against their schema
> fix(pdm): add missing `shell` properties on added `pdm/release` steps

- pdm/docker/README.md
- pdm/docker/action.yml
This PR adds support for extra `build-args` and `secrets` parameters to the Docker build command
> Pdm: support extra docker build args and secrets

- pdm/docker/README.md
- pdm/docker/action.yml
Provide support for optional extra `dgoss` parameters (docker run arguments while run the `goss`/`dgoss` test).
> feat(pdm): support `dgoss` extra parameters

- openapi/README.md
- openapi/diff/README.md
- openapi/diff/action.yml
- pdm/doc/build/action.yml
- pdm/init/README.md
- pdm/init/action.yml
- python-app/openapi-diff/action.yaml
Extract the pure OpenAPI diff part into its own `openapi/diff` action.
Adds OpenAPI diff generation to `pdm/doc/build` action if this is a pull-request
> Factorize OpenAPI diff and integrate it to `pdm/doc/build` action

- python-app/docker/action.yml
**Still requires testing please do not merge until is properly tested**
This will allow to build and push [multi-arch docker images](https://github.blog/changelog/2020-09-17-github-container-registry-support-for-multi-arch-images/) in order to support running on non-intel machines. 
This change is supported by the [github action docker-setup-buildx](https://github.com/marketplace/actions/docker-setup-buildx#customizing)
> feat: multi-arch build for python-app

- pdm/doc/build/action.yml
This PRs:
- ensures that we can switch on the reference branch when performing the OpenAPI diff when there are some changes on the working copy (eg. `CHANGELOG.md`)
- ensures that the entire OpenAPI diff is non required to mark a workflow as succeed because there are many reasons that would prevent to make a diff with the base branch:
- OpenAPI generation is broken on the base branch (and PR is trying to fix it)
- the base branch does not have OpenAPI specs generation (because PR is adding it)
> fix(pdm): fix the OpenAPI diff

- pdm/test/action.yml
Fix bad GitHub expression string quoting (only accept single quotes)
> fix(pdm): fix bad quoting in `pdm/test` action

- pdm/init/README.md
- pdm/init/action.yml
- pdm/test/action.yml
Fix Allure report name:
- fix typo in `pdm/init` `identifier` output
- add `branch` output to `pdm/init`
- use the resolved branch in allure report path
Bonus: add an environment file for Allure to parse (includes all run metadata as well as the PR deep link if any)
Sample report: https://vault.allure.green.ledgerlabs.net/allure/reports/805ddd59-06e8-4f52-b2f0-226f5675b8c1/index.html (miss `branch` which is part of this PR)
> Fixes Allure report name in `pdm/test`

- openapi/diff/action.yml
Self-hosted runners deny permission on `bump-cli` global install so this PR makes it local.
([Sample failure](https://github.com/LedgerHQ/vault-platform-manager/actions/runs/9649997910/job/26614745797?pr=258#step:3:893))
> fix(openapi-diff): fix permissions on self-hosted runners

- openapi/diff/action.yml
- pdm/test/action.yml
- remove the visible `\n` from OpenAPI diff comment
- always keep the `@<branch>` suffix (was already the case due to a bug, so keep it as it is actually useful)
> Small adjustments

- pdm/release/README.md
- pdm/release/action.yml
Given release check docker image using `goss`/`dgoss`, it also requires `dgoss-args` too.
> fix(pdm): release requires dgoss-args too

- .github/dependabot.yml
- allure/generate/README.md
- allure/generate/action.yml
- allure/upload/README.md
- allure/upload/action.yml
- pdm/init/README.md
- pdm/init/action.yml
- pdm/test/README.md
- pdm/test/action.yml
Add support for matrix testing in `pdm/test` action.
Includes `allure/upload` and `allure/generate` supporting separate result upload and report generate for multiple results.
Due to the number of input parameters being limited to 10, all Allure parameters are now environment variables in `pdm/test` action
Fixes:
- coverage reports aggregation
- Allure reports parallel upload and aggregation
- A single report comment (instead of 1 by matrix job and for each report type)
Here's some sample runs:
- [library testing against multiple Python version](https://github.com/LedgerHQ/les-copier-demo/actions/runs/10631011298)
- [generic Python project without matrix testing](https://github.com/LedgerHQ/les-copier-demo/actions/runs/10631883510) (ensure no regressions)
> [!NOTE]
> Actions step diplay …
> PDM: Support for matrix testing

- pdm/test/action.yml
In projects not using Allure, `reports/allure.uuid*` does not exist and `cat reports/allure.uuid*` fails:
cat: 'reports/allure.uuid*': No such file or directory
As an empty UUID list is supported in the next steps of the workflow (using `if: steps.allure-data.outputs.uuids`), ignoring the error `cat` seems to be enough to fix this issue.
Fixes: 7d2b099fe06e ("PDM: Support for matrix testing (#226)")
> fix(pdm/test): do not fail when Allure is not used

- pdm/release/README.md
- pdm/release/action.yml
Support JFrog Artifactory publication in `pdm/release`.
Workflow need to have the proper permissions (authorized on artifactory and OIDC permissions)
> feat(pdm): support JFrog Artifactory publication on release

- pdm/release/action.yml
Remove the `/simple` path fragment from JFrog Artifactory (is part of the PyPI protocol and shouldn't be specified)
> fix(pdm): remove the /simple from the Artifactory URL

- pdm/release/pre/README.md
- pdm/release/pre/action.yml
Extract the `Pre-conditions check` workflow from `python.copier` as a reusable action.
Also added a clear message to explain that CI need to be green 🟢 to run a release.
> feat(pdm/release): package the pre-conditions checks as a reusable action `pdm/release/pre`

- pdm/doc/build/action.yml
- pdm/doc/publish/action.yml
- pdm/docker/action.yml
- pdm/release/action.yml
- pdm/release/pre/action.yml
- pdm/test/action.yml
- always display proper name on `bash` steps (help to understand what happened and where it has failed exactly)
- remove the `@main` suffix on `main` branch Allure report (easier to distinguish from branch report, less cluttered listing). Supersedes #235 
- Ensure release always reach cleanup in case of failure so we don't let half-baked releases needing to manually clean
- Bail off all steps after failure when possible
- Add JFrog Artifactory cleanup in case of failure
- JFrog Artifactory repository is now an input parameter
- Do not fail on missing documentation
- successful release: https://github.com/LedgerHQ/les-copier-demo/actions/runs/10745129557
- cleanup on tag failure: https://github.com/LedgerHQ/les-copier-demo/actions/runs/10744133372
- cleanup Nexus on JFrog failure: …
> PDM workflows: cleaner and safer

- pdm/init/action.yml
`pdm` raises a `.netrc` related warning in case of credentials not found.
This PR ensure that every operation raising a warning has the internal repository credentials
> fix(pdm): remove some  warnings to due to missing credentials

- pdm/release/action.yml
GemFury delete action does not work with standard Python releases (aka. both sources distribution and wheel) by default, as it sees it as 2 distinct versions with the same specifiers.
This PR delete them both by ID.
> fix(pdm/release): Ensures GemFury cleanup works with sdist+wheel release

- pdm/test/action.yml
Comment using the provided (and required) PAT to avoid the need for extra permissions on the callers (workflows using this action)
> fix(pdm): comment using the provided PAT

- pdm/release/action.yml
> fix(pdm/release): fix documentation of input `github-token`

- python-app/README.md
- python-app/docker/action.yml
- python-app/goss/action.yml
- python-app/init/action.yml
- python-app/openapi-diff/action.yaml
Opt-in support for JFrog Artifactory on `python-app` (consume libs from, publish images to, attest and sign images).
Triggered by `JFROG_REPOSITORY` and `JFROG_DOCKER_REPOSITORY` environment variable.
VG-21684
- https://github.com/LedgerHQ/vault-api-gateway/actions/runs/11347483550/job/31562035776?pr=689
- https://github.com/LedgerHQ/vault-api-gateway/actions/runs/11347483535/job/31558973191?pr=689
- https://github.com/LedgerHQ/vault-api-gateway/actions/runs/11346063232/job/31554299863?pr=690
- https://github.com/LedgerHQ/vault-api-gateway/actions/runs/11346063216/job/31554299855?pr=690
> feat(jfrog): adds opt-in Jfrog Artifactory support on `python-app` (VG-21684)

- pdm/test/action.yml
#249 had breaking change on parameter names.
This PR applies the updated naming
> fix(pdm/test): update `actions-comment-pull-request` parameters to v3 naming

- pdm/docker/README.md
- pdm/docker/action.yml
- python-app/README.md
- python-app/docker/action.yml
Try to authenticate early on Docker Hub when possible (ie. credentials available) to avoid rate limiting while pulling images.
> Early Docker Hub authentication if possible to avoid rate limiting

- pdm/docker/README.md
- pdm/docker/action.yml
- pdm/release/README.md
- pdm/release/action.yml
This PR allows repositories to publish an extra docker image.
In this case, it needs to follow this convention:
- a `Dockerfile.<name>` file
- optionally, a `<name>` directory containing `goss.yaml` and `goss_wait.yaml` if supported
- CI workflow will have an extra docker job with `name` and `suffix` parameter set to `name`
- Release workflow will have the `extra_docker` parameter set to `<name>`
Published images will be:
- `ghcr.io/ledgerhq/<name>:<version>`
- `jfrog.ledgerlabs.net/<jfrog repo>/<name>:<version>`
Where `<version>` is in sync with nominal image.
The resulting image will have proper labels and annotations (annotations support have been added in this PR)
Resulting workflows:
- CI: https://github.com/LedgerHQ/les-copier-demo/actions/runs/11918640466
- Release: …
> feat(pdm): supports repository with an extra docker image

- pdm/release/README.md
- pdm/release/action.yml
Allows to optionally override the docker image name in `pdm/release`
> feat(pdm): allows to override the generated docker image name release

- pdm/init/README.md
- pdm/init/action.yml
- pdm/release/README.md
- pdm/release/action.yml
Detect and expose JFrog Artifactory support as well as distribution kind in `init`.
Deprecate `pdm/release` `kind` parameter
- backward compatible:
- CI: https://github.com/LedgerHQ/les-copier-demo/actions/runs/12139059509
- Release: https://github.com/LedgerHQ/les-copier-demo/actions/runs/12139919227
- CI without `jFROG_REPOSITORY` var: https://github.com/LedgerHQ/les-copier-demo/actions/runs/12140111126
- Release without `kind`: https://github.com/LedgerHQ/les-copier-demo/actions/runs/12140492728
> feat(pdm): detect libraries and JFrog support to avoid failures

- pdm/docker/action.yml
- pdm/init/action.yml
Avoid JFrog double authentication:
- faster
- removes some warnings on cleanup
> fix(jfrog): avoid double authentication

- pdm/doc/publish/action.yml
To avoid filling `gh-pages` branch, reaching GitHub pages size limitation and to unclutter the version selector, we only keep the latest documentation version by `<major>.<minor>`.
Same change as https://github.com/LedgerHQ/ledger-vault-api/pull/5134 (Gate has reach `gh-pages` size limit)
> fix(pdm): only keep latest documentation by `<major>.<minor>`

- pdm/test/action.yml
When self-hosted runners are brutally and savagely restarted during a `repoort` job, you have to rerun the entire workflow because artifacts were already merged.
This makes the `report` job replayable even artifacts have been merged
> fix(pdm): allow to replaying the `report` job in case of savage runner restart

- pdm/docker/action.yml
Fixes bad JFROG secrets on 2n docker build-push that only happens for single-pass docker builds without `goss`.
The JFrog login step is only executed if credentials are not present in the environment. We need to check always check and fetch credentials from the environment.
> fix(pdm): fix bad JFROG secrets on 2n docker build-push

- pdm/release/action.yml
This PR fixes the OpenAPI generation on release, which was still binded to the deprecated `kind` parameter.
> fix(pdm): restore the OpenAPI doc generation on release

- python-app/openapi-diff/action.yaml
should fix error "Unable to find candidates for pdm-backend."
> fix: choose python version for openapi diff

- openapi/diff/README.md
- openapi/diff/action.yml
- pdm/doc/build/README.md
- pdm/doc/build/action.yml
- pdm/doc/publish/README.md
- pdm/doc/publish/action.yml
- pdm/docker/README.md
- pdm/docker/action.yml
- pdm/init/README.md
- pdm/init/action.yml
- pdm/release/README.md
- pdm/release/pre/README.md
- pdm/release/pre/action.yml
- pdm/test/README.md
- pdm/test/action.yml
This PR ensure we can use both the `CI_BOT_TOKEN` and `github.token` with proper permission in all `pdm` actions as well as in the `openapi/diff` action.
It also documents all required permissions for those actions.
> [!NOTE]
> `pdm/release` action is still requiring a PAT as it relies on specific permissions in the repository setting to be able to push on the branch without a PR. I might need some investigation to ensure we can use the builtin `github.token`
Also, PyPI token deprecation has been properly flagged and documented
> fix(pdm): `github-token` and permissions consistency

- pdm/docker/README.md
- pdm/release/README.md
Document the required `packages: write` permission for jdocker publication to ghcr.io
> doc(pdm): document the `packages: write` permission for Docker image publication to ghcr.io

- pdm/doc/build/action.yml
Ensure that following tasks can actually access workspace assets from the current ref and still read the openapi spec from its expected location.
> [!NOTE]
> This suggest that maybe the OpenAPI generation and diff should be splitted into their own action/job
> fix(pdm): restore the workspace after OpenAPI diff for next tasks

- pdm/docker/action.yml
This should prepare for the next GitHub Legacy cache brownout (April 8th) by forcing the latest BuildX version instead of relying on the one providing by the runner.
See:
- https://github.blog/changelog/2025-03-20-notification-of-upcoming-breaking-changes-in-github-actions/#decommissioned-cache-service-brownouts for the context
- https://github.com/docker/build-push-action/issues/1345#issuecomment-2770572479 for the solution
> fix(pdm): force the latest Docker BuildX

- pdm/doc/README.md
- pdm/doc/action.yml
- pdm/doc/build/README.md
- pdm/doc/build/action.yml
- pdm/doc/publish/README.md
- pdm/doc/publish/action.yml
- pdm/docker/README.md
- pdm/docker/action.yml
- pdm/init/README.md
- pdm/init/action.yml
- pdm/openapi/README.md
- pdm/openapi/action.yml
- pdm/release/action.yml
- pdm/test/README.md
- pdm/test/action.yml
GemFury publication as well as the use of `pypi-token` has been deprecated for the past year. It's now time to drop it (and remove those warnings in the builds)
> refactor(pdm): drop the deprecated support for GemFury
